### ISSUE TITLE
Fail to decode event data with python

### ISSUE THREAD

**Issue by AndyFrancesco29** [ros-event-camera/event_camera_py#16]
Hi,
I am new with ROS. I have built the repository in ROS, but when I run python I still get "ModuleNotFoundError: No module named 'event_camera_py'". Is there anything I missed? Thank you.

**Comment by berndpfrommer** [comment]
Is this on ros1 or ros2?
Did you source devel/setup.bash or install/setup.bash in your workspace?

**Comment by AndyFrancesco29** [comment]
Thanks for your answer. Now I am having a new problem. When I run the example, I got error:

Traceback (most recent call last):
  File "<string>", line 19, in <module>
ModuleNotFoundError: No module named 'rpyutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 27, in <module>
ModuleNotFoundError: No module named 'event_camera_py._event_camera_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_1.py", line 29, in <module>
    from event_camera_py import Decoder  # noqa: E402  (suppress flake8 error)
  File "/home/aiot/event_camera_py_ws/devel/lib/python3/dist-packages/event_camera_py/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 30, in <module>
ModuleNotFoundError: No module named '_event_camera_py'

I am using ROS1. Should I install any other packages?

**Comment by berndpfrommer** [comment]
Just tested it again and the import works fine in my workspace.
The rpyutils module is not part of ROS1, only ROS2. But if you look at the __init__.py script you can see that it handles the case of missing rpyutils, so it should work under ROS1.
Please do the following:
1) clean your workspace (remove "devel" and "build" at the top)
2) catkin build
3) source /opt/ros/noetic/setup.bash
4) source ./devel/setup.bash

Start python3 and do import:
```
python3
>> from event_camera_py import Decoder
```
If this doesn't work, cut and paste the screen output from all these commands into a text file and post them.

**Comment by AndyFrancesco29** [comment]
Thanks for your advice. I found the problem here. I have installed anaconda in my system. It works in the base environment but when I create a new environment, it seems it cannot work in that environment.

Also, may I ask what does trig_events and cd_events mean in the example? I record a rosbag from one camera and only cd_events has value in it.

**Comment by AndyFrancesco29** [comment]
Also, may I ask what is logic for decoding the rosbag? When I look at the msg in rosbag iteration, I found there is just a single list in "events". So how to transform this array to (x, y, p, t)?

**Comment by berndpfrommer** [comment]
Not sure what you mean with this last question. Does this code snippet (from the README) not work for you?
```python
import rosbag
from event_camera_py import Decoder

topic = '/event_camera/events'
bag = rosbag.Bag('foo.bag')
decoder = Decoder()

for topic, msg, t in bag.read_messages(topics=topic):
    decoder.decode_bytes(msg.encoding, msg.width, msg.height,
	                     msg.time_base, msg.events)
    cd_events = decoder.get_cd_events()
    print(cd_events)
    trig_events = decoder.get_ext_trig_events()
    print(trig_events)
```

**Comment by berndpfrommer** [comment]
Oh, and for the benefit of others: is the original issue you posted now resolved, and why did it not work for you?

**Comment by AndyFrancesco29** [comment]
Yes the origin issue is solved. It is because of the anaconda environment. I change the environment to the base and it works.

For the last question, I mean when I print the msg, I find something like:
events: [164, 141, 164, 141, 164, 141, 164, 141, 164, 141, 164, 141, 53, 110, 96, 2, 39, 34, 164, 141, 164, 141, 164, 141, 164, 141, 164, 141, 164, 141, 164, 141, 160, 110, 20, 224, 1, 240, 0, 240, 0, 112, 22, 224, 1, 240, 0, 240, 0, 112, 255, 224, 164, 141, 164, 141, 164, 141, 164, 141, 164, 141, 164, 141, 13, 111, ...] 1706342545760574767

So how the decoder transform this into format (x, y, p, t)?

**Comment by berndpfrommer** [comment]
The decoding is done by the c++ code in event_camera_codecs, which is
wrapped by event_camera_py. You will have to look at the source code to see
the exact mechanics.

**Comment by berndpfrommer** [comment]
Will close this issue if there is no more activity.

**Comment by AndyFrancesco29** [comment]
Thanks for your answer. I will close this issue.
